teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.3
      y: 0.3
    scale_linear_turbo:
      x: 1.0
      y: 1.0

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 1.5
    
    enable_button: 5
    enable_turbo_button: 7
